### ISSUE TITLE
publish in pycaret

### ISSUE THREAD

**Issue by celestinoxp** [glevv/obscure_stats#55]
I found this repository by chance, and I found it very interesting, however, for less experienced users it can be a little confusing.

Proposal: what do you think about trying to integrate this package into the well-known pycaret?

The pycaret package uses the scikit-learn, catboost, lightgbm and xgboost models.

This post is just an idea taking into account that pycaret does everything automatically for inexperienced users, so it would be an added value to be able to improve the performance of algorithms based on data automatically created by this package.

It's just an idea...

**Comment by glevv** [comment]
Greetings!

Right now, I know very little about pycaret since I used it only once a long time ago. I will need some time to do some research about the feasibility and sensibility of such a move.

Thank you for the idea

**Comment by celestinoxp** [comment]
ping

**Comment by glevv** [comment]
After careful consideration and research, I don't think it's possible due to the following reasons:
 - `PyCaret` is primarily designed to provide a streamlined machine learning experience for users of all skill levels. While this library might offer some niche statistical functions, it doesn't directly align with PyCaret's core objectives of user-friendliness and accessibility in the ML domain.
 - Integrating `obscure_stats` into the `PyCaret` codebase would be an enormous task because our environment managers, dependencies, formatters, etc. are completely different. It will also need extensive testing and maintenance efforts to ensure seamless compatibility and avoid potential conflicts. I don't think it is feasible right now.

I appreciate the idea, but we are not going in this direction.
